{ inputs, config, pkgs, ... }:
  let
    breezeDark = "${pkgs.kdePackages.breeze}/share/color-schemes/BreezeDark.colors";
  in {
  xdg.dataFile."color-schemes/base16.colors".text = ''
    # This file is generated by Home Manager.
    # Base: Breeze Dark, accents replaced with base16-mocha

    # Include original Breeze Dark content
    ${builtins.readFile breezeDark}

    [General]
    ColorScheme=Base16
    Name=Base16

    [Colors:Window]
    BackgroundNormal=#${config.lib.stylix.colors.base00}

    # Override Selection colors
    [Colors:Selection]
    BackgroundNormal=#${config.lib.stylix.colors.base02}
    ForegroundNormal=#${config.lib.stylix.colors.base05}

    # Override Link colors
    [Colors:Link]
    ForegroundNormal=#${config.lib.stylix.colors.base0D}
    ForegroundVisited=#${config.lib.stylix.colors.base0E}

    # Override Complementary (Negative/Neutral/Positive) colors
    [Colors:Complementary]
    NegativeText=#${config.lib.stylix.colors.base08}
    NeutralText=#${config.lib.stylix.colors.base09}
    PositiveText=#${config.lib.stylix.colors.base0B}
  '';
}
