{ inputs, config, ... }: {
  xdg.configFile."qt5ct/colors/base16.conf".text = ''
    [ColorScheme]
    active_colors=#ff${config.lib.stylix.colors.base05}, #ff${config.lib.stylix.colors.base01}, #ff${config.lib.stylix.colors.base01}, #ff${config.lib.stylix.colors.base05}, #ff${config.lib.stylix.colors.base03}, #ff${config.lib.stylix.colors.base04}, #ff${config.lib.stylix.colors.base05}, #ff${config.lib.stylix.colors.base06}, #ff${config.lib.stylix.colors.base05}, #ff${config.lib.stylix.colors.base01}, #ff3b3228, #ff${config.lib.stylix.colors.base03}, #ff${config.lib.stylix.colors.base02}, #ff${config.lib.stylix.colors.base05}, #ff${config.lib.stylix.colors.base09}, #ff${config.lib.stylix.colors.base08}, #ff${config.lib.stylix.colors.base02}, #ff${config.lib.stylix.colors.base05}, #ff${config.lib.stylix.colors.base01}, #ff${config.lib.stylix.colors.base05}, #8f${config.lib.stylix.colors.base05}
    disabled_colors=#ff${config.lib.stylix.colors.base0F}, #ff${config.lib.stylix.colors.base01}, #ff${config.lib.stylix.colors.base01}, #ff${config.lib.stylix.colors.base05}, #ff${config.lib.stylix.colors.base03}, #ff${config.lib.stylix.colors.base04}, #ff${config.lib.stylix.colors.base0F}, #ff${config.lib.stylix.colors.base0F}, #ff${config.lib.stylix.colors.base0F}, #ff${config.lib.stylix.colors.base01}, #ff3b3228, #ff${config.lib.stylix.colors.base03}, #ff${config.lib.stylix.colors.base02}, #ff${config.lib.stylix.colors.base05}, #ff${config.lib.stylix.colors.base09}, #ff${config.lib.stylix.colors.base08}, #ff${config.lib.stylix.colors.base02}, #ff${config.lib.stylix.colors.base05}, #ff${config.lib.stylix.colors.base01}, #ff${config.lib.stylix.colors.base0F}, #8f${config.lib.stylix.colors.base0F}
    inactive_colors=#ff${config.lib.stylix.colors.base05}, #ff${config.lib.stylix.colors.base01}, #ff${config.lib.stylix.colors.base01}, #ff${config.lib.stylix.colors.base05}, #ff${config.lib.stylix.colors.base03}, #ff${config.lib.stylix.colors.base04}, #ff${config.lib.stylix.colors.base05}, #ff${config.lib.stylix.colors.base06}, #ff${config.lib.stylix.colors.base05}, #ff${config.lib.stylix.colors.base01}, #ff3b3228, #ff${config.lib.stylix.colors.base03}, #ff${config.lib.stylix.colors.base02}, #ff${config.lib.stylix.colors.base05}, #ff${config.lib.stylix.colors.base09}, #ff${config.lib.stylix.colors.base08}, #ff${config.lib.stylix.colors.base02}, #ff${config.lib.stylix.colors.base05}, #ff${config.lib.stylix.colors.base01}, #ff${config.lib.stylix.colors.base05}, #8f${config.lib.stylix.colors.base05}
  '';

  xdg.configFile."qt6ct/colors/base16.conf".text = config.xdg.configFile."qt5ct/colors/base16.conf".text;
}
