#!/usr/bin/env bash

CONF_PATH="${HOME}/.config/mango/monitors.conf"

usage() {
  echo "Usage: $0 [-o output_path]"
  echo "  -o FILE   Write config to FILE instead of ${CONF_PATH}"
  exit 1
}

while getopts ":o:h" opt; do
  case "$opt" in
    o) CONF_PATH="$OPTARG" ;;
    h) usage ;;
    *) usage ;;
  esac
done

command -v wlr-randr >/dev/null 2>&1 || { echo "Error: wlr-randr not found in PATH" >&2; exit 1; }
command -v jq        >/dev/null 2>&1 || { echo "Error: jq not found (install it, e.g. 'sudo pacman -S jq')" >&2; exit 1; }
command -v mmsg      >/dev/null 2>&1 || { echo "Error: mmsg not found in PATH" >&2; exit 1; }

RAW_JSON="$(wlr-randr --json)"

if [[ -z "$RAW_JSON" ]]; then
  echo "Error: wlr-randr returned no output" >&2
  exit 1
fi

# HDR status per output, from mmsg (wlr-randr doesn't expose this).
# Falls back to an empty map if the query fails, so every output is
# treated as "unknown" below rather than silently forced to hdr:0.
HDR_MAP="$(mmsg get all-monitors 2>/dev/null | jq -c '[.monitors[] | {(.name): .is_hdr}] | add // {}' 2>/dev/null)"
[[ -n "$HDR_MAP" ]] || HDR_MAP='{}'

# For each enabled output, pull from active mode and build a monitorrule line.
# HDR on/off comes from mmsg's is_hdr. mmsg doesn't report the actual
# hdr_max_lum/hdr_max_avg_lum (that's EDID-derived), so we fill in
# reasonable placeholder defaults when HDR is detected on; if mmsg has no
# entry at all for an output, we leave a marker and fall back to whatever
# was already in the config (see merge step below) instead of guessing.
RULES="$(echo "$RAW_JSON" | jq -r --argjson hdrmap "$HDR_MAP" '
  .[]
  | select(.enabled == true)
  | . as $o
  | ($o.modes[] | select(.current == true)) as $m
  | ($hdrmap | has($o.name)) as $known
  | (if $known then $hdrmap[$o.name] else false end) as $hdr
  | "monitorrule=name:^\($o.name)$,width:\($m.width),height:\($m.height),refresh:\($m.refresh | (. * 1000 | round) / 1000),x:\($o.position.x),y:\($o.position.y),scale:\($o.scale),"
    + (if ($known | not) then "hdr:UNKNOWN"
       elif $hdr then "hdr:1,hdr_max_lum:1200,hdr_max_avg_lum:1000"
       else "hdr:0" end)
')"

SKIPPED="$(echo "$RAW_JSON" | jq -r '
  .[]
  | select(.enabled == false)
  | .name
')"

# Keep track of existing per-monitor lines/hdr so we can carry settings
# forward for disabled outputs, and fall back for outputs mmsg has no
# HDR info for.
declare -A EXISTING_HDR=()
declare -A EXISTING_LINES=()
if [[ -f "$CONF_PATH" ]]; then
  while IFS= read -r line; do
    [[ "$line" == monitorrule=* ]] || continue
    name="$(echo "$line" | grep -oP '(?<=name:\^)[^$]+(?=\$,)' || true)"
    hdr="$(echo "$line" | grep -oP '(?<=hdr:)[01]' || true)"
    [[ -n "$name" ]] || continue
    EXISTING_LINES["$name"]="$line"
    [[ -n "$hdr" ]] && EXISTING_HDR["$name"]="$hdr"
  done < "$CONF_PATH"
fi

# Resolve any "hdr:UNKNOWN" markers: reuse the previous full line (so a
# manually-tuned hdr_max_lum survives) if we have one, otherwise default
# to hdr:0.
if [[ -n "$RULES" ]]; then
  MERGED_RULES=""
  while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    if [[ "$line" == *"hdr:UNKNOWN"* ]]; then
      name="$(echo "$line" | grep -oP '(?<=name:\^)[^$]+(?=\$,)' || true)"
      if [[ -n "$name" && -n "${EXISTING_LINES[$name]:-}" ]]; then
        line="${EXISTING_LINES[$name]}"
      else
        line="${line/hdr:UNKNOWN/hdr:0}"
      fi
    fi
    MERGED_RULES+="${line}"$'\n'
  done <<< "$RULES"
  RULES="${MERGED_RULES%$'\n'}"
fi

# Preserve HDR status monitors that are currently disabled/disconnected
CARRIED_OVER=""
if [[ -n "$SKIPPED" && ${#EXISTING_LINES[@]} -gt 0 ]]; then
  while IFS= read -r name; do
    [[ -z "$name" ]] && continue
    if [[ -n "${EXISTING_LINES[$name]:-}" ]]; then
      CARRIED_OVER+="${EXISTING_LINES[$name]}"$'\n'
    fi
  done <<< "$SKIPPED"
  CARRIED_OVER="${CARRIED_OVER%$'\n'}"
fi

{
  echo "# Generated by gen-monitors-conf.sh"
  echo
  if [[ -n "$RULES" ]]; then
    echo "$RULES"
  else
    echo "# No enabled outputs were found."
  fi
  if [[ -n "$CARRIED_OVER" ]]; then
    echo
    echo "# Currently disabled/disconnected, but carried over from the"
    echo "# previous config (including hdr) so settings aren't lost:"
    echo "$CARRIED_OVER"
  fi
  if [[ -n "$SKIPPED" ]]; then
    NO_PRIOR_RULE=""
    while IFS= read -r name; do
      [[ -z "$name" ]] && continue
      [[ -n "${EXISTING_LINES[$name]:-}" ]] || NO_PRIOR_RULE+="${name}"$'\n'
    done <<< "$SKIPPED"
    NO_PRIOR_RULE="${NO_PRIOR_RULE%$'\n'}"
    if [[ -n "$NO_PRIOR_RULE" ]]; then
      echo
      echo "# Skipped (currently disabled/disconnected, no previous rule to carry over):"
      while IFS= read -r name; do
        echo "#   $name"
      done <<< "$NO_PRIOR_RULE"
    fi
  fi
} > /tmp/monitors.conf.new

# Get the focused client's info before reload
client_json=$(mmsg get focusing-client)
client_id=$(jq -r '.id' <<< "$client_json")
was_fullscreen=$(jq -r '.is_fullscreen' <<< "$client_json")

# Can drop fullscreen state
mkdir -p "$(dirname "$CONF_PATH")"
mv /tmp/monitors.conf.new "$CONF_PATH"

# Set DISPLAY=:1 on start, then remove to avoid breaking the next session startup (env is preserved during existing session...)
echo "env=DISPLAY,:1" >> "$CONF_PATH"
mmsg dispatch reload_config
sed -i '/^env=DISPLAY,:1$/d' "$CONF_PATH"

# Restore fullscren if it was lost
if [[ "$was_fullscreen" == "true" ]]; then
  # Re-check current state after reload — don't just assume it dropped
  now_json=$(mmsg get client "$client_id")
  now_fullscreen=$(jq -r '.is_fullscreen' <<< "$now_json")

  if [[ "$now_fullscreen" == "false" ]]; then
    mmsg dispatch togglefullscreen client,"$client_id"
  fi
fi
