#!/usr/bin/env bash

CONF_PATH="${HOME}/.config/mango/monitors.conf"
DRY_RUN=0

usage() {
  echo "Usage: $0 [-o output_path] [-n]"
  echo "  -o FILE   Write config to FILE instead of ${CONF_PATH}"
  echo "  -n        Dry run: print generated config to stdout, don't write"
  exit 1
}

while getopts ":o:nh" opt; do
  case "$opt" in
    o) CONF_PATH="$OPTARG" ;;
    n) DRY_RUN=1 ;;
    h) usage ;;
    *) usage ;;
  esac
done

command -v wlr-randr >/dev/null 2>&1 || { echo "Error: wlr-randr not found in PATH" >&2; exit 1; }
command -v jq        >/dev/null 2>&1 || { echo "Error: jq not found (install it, e.g. 'sudo pacman -S jq')" >&2; exit 1; }

RAW_JSON="$(wlr-randr --json)"

if [[ -z "$RAW_JSON" ]]; then
  echo "Error: wlr-randr returned no output" >&2
  exit 1
fi

# For each enabled output, pull from active mode and build a monitorrule line.
RULES="$(echo "$RAW_JSON" | jq -r '
  .[]
  | select(.enabled == true)
  | . as $o
  | ($o.modes[] | select(.current == true)) as $m
  | "monitorrule=name:^\($o.name)$,width:\($m.width),height:\($m.height),refresh:\($m.refresh | (. * 1000 | round) / 1000),x:\($o.position.x),y:\($o.position.y),scale:\($o.scale),hdr:0"
')"

SKIPPED="$(echo "$RAW_JSON" | jq -r '
  .[]
  | select(.enabled == false)
  | .name
')"

# Preserve each monitor's existing hdr:0/1 flag from the current config
# file (if any) instead of blowing it away back to the hdr:0 default.
declare -A EXISTING_HDR=()
declare -A EXISTING_LINES=()
if [[ -f "$CONF_PATH" ]]; then
  while IFS= read -r line; do
    [[ "$line" == monitorrule=* ]] || continue
    name="$(echo "$line" | grep -oP '(?<=name:\^)[^$]+(?=\$,)' || true)"
    hdr="$(echo "$line" | grep -oP '(?<=hdr:)[01]' || true)"
    [[ -n "$name" ]] || continue
    EXISTING_LINES["$name"]="$line"
    [[ -n "$hdr" ]] && EXISTING_HDR["$name"]="$hdr"
  done < "$CONF_PATH"
fi

if [[ -n "$RULES" && ${#EXISTING_HDR[@]} -gt 0 ]]; then
  MERGED_RULES=""
  while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    name="$(echo "$line" | grep -oP '(?<=name:\^)[^$]+(?=\$,)' || true)"
    if [[ -n "$name" && -n "${EXISTING_HDR[$name]:-}" ]]; then
      line="${line/hdr:0/hdr:${EXISTING_HDR[$name]}}"
    fi
    MERGED_RULES+="${line}"$'\n'
  done <<< "$RULES"
  RULES="${MERGED_RULES%$'\n'}"
fi

# Preserve HDR status monitors that are currently disabled/disconnected
CARRIED_OVER=""
if [[ -n "$SKIPPED" && ${#EXISTING_LINES[@]} -gt 0 ]]; then
  while IFS= read -r name; do
    [[ -z "$name" ]] && continue
    if [[ -n "${EXISTING_LINES[$name]:-}" ]]; then
      CARRIED_OVER+="${EXISTING_LINES[$name]}"$'\n'
    fi
  done <<< "$SKIPPED"
  CARRIED_OVER="${CARRIED_OVER%$'\n'}"
fi

{
  echo "# Generated by gen-monitors-conf.sh"
  echo
  if [[ -n "$RULES" ]]; then
    echo "$RULES"
  else
    echo "# No enabled outputs were found."
  fi
  if [[ -n "$CARRIED_OVER" ]]; then
    echo
    echo "# Currently disabled/disconnected, but carried over from the"
    echo "# previous config (including hdr) so settings aren't lost:"
    echo "$CARRIED_OVER"
  fi
  if [[ -n "$SKIPPED" ]]; then
    NO_PRIOR_RULE=""
    while IFS= read -r name; do
      [[ -z "$name" ]] && continue
      [[ -n "${EXISTING_LINES[$name]:-}" ]] || NO_PRIOR_RULE+="${name}"$'\n'
    done <<< "$SKIPPED"
    NO_PRIOR_RULE="${NO_PRIOR_RULE%$'\n'}"
    if [[ -n "$NO_PRIOR_RULE" ]]; then
      echo
      echo "# Skipped (currently disabled/disconnected, no previous rule to carry over):"
      while IFS= read -r name; do
        echo "#   $name"
      done <<< "$NO_PRIOR_RULE"
    fi
  fi
} > /tmp/monitors.conf.new

mkdir -p "$(dirname "$CONF_PATH")"
mv /tmp/monitors.conf.new "$CONF_PATH"

# Set DISPLAY=:1 on start, then remove to avoid breaking the next session startup (env is preserved during existing session...)
echo "env=DISPLAY,:1" >> "$CONF_PATH"
mmsg dispatch reload_config
sed -i '/^env=DISPLAY,:1$/d' "$CONF_PATH"