services:
  byparr:
    # More actively-developed. The dev encourages "main" over "latest"
    image: ghcr.io/thephaseless/byparr:main
    container_name: byparr
    network_mode: "container:gluetun"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=EST
      #- PORT=8192
    #ports:
    #  - "${PORT:-8192}:8191"
    init: true
    restart: unless-stopped

#networks:
#    default:
#        name: flaresolverr_default
#        driver: bridge
