services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "container:gluetun"
    environment:
      - PUID=MEDIA_UID
      - PGID=MEDIA_GID
      - TZ=EST
      - WEBUI_PORT=43000
      - TORRENTING_PORT=31552
    volumes:
      - /srv/docker/qbittorrent/config:/config
      - /mnt/ext/Media/qbittorrent/downloads:/downloads
    #ports:
    #  - 8080:8080
    #  - 6881:6881
    #  - 6881:6881/udp
    restart: unless-stopped
