version: '3.7'
services:
  suwayomi:
    image: ghcr.io/suwayomi/tachidesk:latest
    #build: .
    environment:
      - TZ=Etc/UTC # Use TZ database name from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      # Comment these out if you do not use the flaresolverr container at the bottom of this file
      - FLARESOLVERR_ENABLED=true
      - FLARESOLVERR_URL=http://flaresolverr:8191
      - AUTO_DOWNLOAD_CHAPTERS=true
      - AUTO_DOWNLOAD_EXCLUDE_UNREAD=false
      - UPDATE_EXCLUDE_UNREAD=false
      - UPDATE_EXCLUDE_STARTED=false
      - DOWNLOAD_AS_CBZ=true
      - EXTENSION_REPOS=["https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json"]
#  #################################################################################################
#
#    !!! IMPORTANT !!!
#     - server settings can be changed during runtime in the WebUI
#     - providing an environment variable will OVERWRITE the current setting value when starting the container
#
#  #################################################################################################
#
#    example for setting env vars:
#
#      - BIND_IP=0.0.0.0
#      - BIND_PORT=4567
#      - SOCKS_PROXY_ENABLED=false
#      - DOWNLOAD_AS_CBZ=true
#      - BASIC_AUTH_ENABLED=true
#      - BASIC_AUTH_USERNAME=manga
#      - BASIC_AUTH_PASSWORD=hello123
#      - EXTENSION_REPOS=["http://github.com/orginazation-name/repo-name", "http://github.com/orginazation-name-2/repo-name-2"]
    user: "MEDIA_UID:MEDIA_GID"
    volumes:
      - /srv/docker/suwayomi/data:/home/suwayomi/.local/share/Tachidesk
      - /mnt/ext/Media/Manga:/home/suwayomi/.local/share/Tachidesk/downloads/
    ports:
      - "4568:4567"

    networks:
      - flaresolverr_default
    restart: on-failure:3
    cap_add:
      - NET_ADMIN
    dns:
      - 1.1.1.1
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1

networks:
  flaresolverr_default:
    external: true
