# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
let
  # GTX 960
  gpuIDs = [
    #"10de:1401" # Graphics
    #"10de:0fba" # Audio
  ];
in
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" "it87" ]; # For Gigabyte motherboard fan control
  boot.extraModulePackages = with config.boot.kernelPackages; [ it87 ]; # https://www.reddit.com/r/NixOS/comments/1ooa2eh/it87_driver_for_it8613e_not_being_loaded_by/
  # Avoid audio crackle: https://wiki.cachyos.org/features/cachyos_settings/#udev-rules
  boot.kernelParams = [ "snd_hda_intel.power_save=0" "btusb.enable_autosuspend=0" "amdgpu.gpu_recovery=1" "amdgpu.noretry=0" "hid_apple.fnmode=2" ];# ++ [ ("vfio-pci.ids=" + lib.concatStringsSep "," gpuIDs) ];

  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernelPatches = [
    {
      name = "enable-adapter-freesync-0";
      patch = ../../patches/0001-amdgpu-Add-CH7218-PCON-to-the-VRR-whitelist.patch;
    }
    {
      name = "enable-adapter-freesync-1";
      patch = ../../patches/v2-0001-drm-edid-parse-more-info-from-HDMI-Forum-vsdb.patch;
    }
    {
      name = "enable-adapter-freesync-2";
      patch = ../../patches/v2-0002-drm-amd-display-rename-PCON-adaptive-sync-types.patch;
    }
    {
      name = "enable-adapter-freesync-3";
      patch = ../../patches/v2-0003-drm-amd-display-enable-HDMI-VRR-over-PCON.patch;
    }
    #{
    #  name = "force-hdmi-vrr";
    #  patch = ../../patches/0002-amdgpu-force-vrr.patch;
    #}
  ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0fd9baa2-da15-4288-911c-15de4287f4c6";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/0fd9baa2-da15-4288-911c-15de4287f4c6";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9932-D468";
      fsType = "vfat";
    };

  fileSystems."/mnt/WD_BLACK" =
    { device = "dev/disk/by-uuid/38c2bd3d-7f9e-47a5-8385-7b970e6ac656";
      fsType = "btrfs";
      options = [ "noauto" "nosuid" "nodev" "nofail" "x-gvfs-show" ];
    };

  fileSystems."/mnt/WD_BLACK2" =
    { device = "dev/disk/by-uuid/417a6a41-7168-4ad1-b945-6cd820914983";
      fsType = "btrfs";
      options = [ "noauto" "nosuid" "nodev" "nofail" "x-gvfs-show" ];
    };

  fileSystems."/mnt/s860" =
    { device = "dev/disk/by-uuid/4176292a-e20c-4ccb-8b06-14eacd7449b5";
      fsType = "ext4";
      options = [ "nosuid" "nodev" "nofail" "x-gvfs-show" ];
    };

  swapDevices = [{
    device = "/var/lib/swapfile";
    size = 16*1024;
  }];

  zramSwap = {
    enable = true;
    memoryPercent = 30;
  };

  console = {
    # Found in /etc/kbd/consolefonts
    font = "${pkgs.terminus_font}/share/consolefonts/ter-114b.psf.gz";
    packages = with pkgs; [ terminus_font ];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp14s0f3u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp9s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
