
# This is your home-manager configuration file
# Use this to configure your home environment (it replaces ~/.config/nixpkgs/home.nix)
{
  inputs,
  outputs,
  lib,
  config,
  pkgs,
  hostName,
  ...
}: {
  # You can import other home-manager modules here
  imports = [
    inputs.plasma-manager.homeManagerModules.plasma-manager
  ];

  nixpkgs = {
    # You can add overlays here
    overlays = [
      # Add overlays your own flake exports (from overlays and pkgs dir):
      outputs.overlays.additions
      outputs.overlays.modifications
      outputs.overlays.stable-packages
      outputs.overlays.unstable-packages
      outputs.overlays.legacy-packages
    ];
  };

  programs.plasma = {
    enable = true;
    # Generated by "rc2nix" # nix run github:nix-community/plasma-manager"
    shortcuts = {
      "kwin"."Show Desktop" = "none,Meta+D,Peek at Desktop";
      "kwin"."Switch to Desktop 1" = "Meta+1,Ctrl+F1,Switch to Desktop 1";
      "kwin"."Switch to Desktop 2" = "Meta+2,Ctrl+F2,Switch to Desktop 2";
      "kwin"."Switch to Desktop 3" = "Meta+3,Ctrl+F3,Switch to Desktop 3";
      "kwin"."Switch to Desktop 4" = "Meta+4,Ctrl+F4,Switch to Desktop 4";
      "kwin"."Switch to Desktop 5" = "Meta+5,,Switch to Desktop 5";
      "kwin"."Switch to Desktop 6" = "Meta+6,,Switch to Desktop 6";
      "kwin"."Switch to Desktop 7" = "Meta+7,,Switch to Desktop 7";
      "kwin"."Switch to Desktop 8" = "Meta+8,,Switch to Desktop 8";
      "kwin"."Switch to Desktop 9" = "Meta+9,,Switch to Desktop 9";
      "kwin"."Switch to Desktop 10" = "Meta+0,,Switch to Desktop 10";

      "kwin"."Window to Desktop 1" = "Meta+!,,Window to Desktop 1";
      "kwin"."Window to Desktop 2" = "Meta+@,,Window to Desktop 2";
      "kwin"."Window to Desktop 3" = "Meta+#,,Window to Desktop 3";
      "kwin"."Window to Desktop 4" = "Meta+$,,Window to Desktop 4";
      "kwin"."Window to Desktop 5" = "Meta+%,,Window to Desktop 5";
      "kwin"."Window to Desktop 6" = "Meta+^,,Window to Desktop 6";
      "kwin"."Window to Desktop 7" = "Meta+&,,Window to Desktop 7";
      "kwin"."Window to Desktop 8" = "Meta+*,,Window to Desktop 8";
      "kwin"."Window to Desktop 9" = "Meta+(,,Window to Desktop 9";
      "kwin"."Window to Desktop 10" = "Meta+),,Window to Desktop 10";

      # Disable to make way for Desktop shortcuts
      "plasmashell"."activate task manager entry 1" = "none,Meta+1,Activate Task Manager Entry 1";
      "plasmashell"."activate task manager entry 2" = "none,Meta+2,Activate Task Manager Entry 2";
      "plasmashell"."activate task manager entry 3" = "none,Meta+3,Activate Task Manager Entry 3";
      "plasmashell"."activate task manager entry 4" = "none,Meta+4,Activate Task Manager Entry 4";
      "plasmashell"."activate task manager entry 5" = "none,Meta+5,Activate Task Manager Entry 5";
      "plasmashell"."activate task manager entry 6" = "none,Meta+6,Activate Task Manager Entry 6";
      "plasmashell"."activate task manager entry 7" = "none,Meta+7,Activate Task Manager Entry 7";
      "plasmashell"."activate task manager entry 8" = "none,Meta+8,Activate Task Manager Entry 8";
      "plasmashell"."activate task manager entry 9" = "none,Meta+9,Activate Task Manager Entry 9";

      "services/org.kde.krunner.desktop"."_launch" = ["Alt+F2" "Alt+Space" "Meta+D" "Search"];

      "kwin"."Window Close" = ["Alt+F4" "Meta+Shift+Q,Alt+F4,Close Window"];
      "kwin"."Window Maximize" = ["Meta+PgUp" "Meta+F,Meta+PgUp,Maximize Window"];
      
      "kwin"."KrohnkiteBTreeLayout" = "none";
      "kwin"."KrohnkiteColumnsLayout" = "none";
      "kwin"."KrohnkiteDecrease" = "none";
      "kwin"."KrohnkiteFloatAll" = "Meta+Shift+F\\,none\\,Krohnkite: Toggle Float All";
      "kwin"."KrohnkiteFloatingLayout" = "none";
      "kwin"."KrohnkiteFocusDown" = "Meta+Down\\,none\\,Krohnkite: Focus Down";
      "kwin"."KrohnkiteFocusLeft" = "Meta+Left\\,none\\,Krohnkite: Focus Left";
      "kwin"."KrohnkiteFocusNext" = "none";
      "kwin"."KrohnkiteFocusPrev" = "none";
      "kwin"."KrohnkiteFocusRight" = "Meta+Right\\,none\\,Krohnkite: Focus Right";
      "kwin"."KrohnkiteFocusUp" = "Meta+Up\\,none\\,Krohnkite: Focus Up";
      "kwin"."KrohnkiteGrowHeight" = "Meta+Ctrl+J\\,none\\,Krohnkite: Grow Height";
      "kwin"."KrohnkiteIncrease" = "Meta+I\\,none\\,Krohnkite: Increase";
      "kwin"."KrohnkiteMonocleLayout" = "Meta+M\\,none\\,Krohnkite: Monocle Layout";
      "kwin"."KrohnkiteNextLayout" = "Meta+\\\\\\,none\\,Krohnkite: Next Layout";
      "kwin"."KrohnkitePreviousLayout" = "Meta+|\\,none\\,Krohnkite: Previous Layout";
      "kwin"."KrohnkiteQuarterLayout" = "none";
      "kwin"."KrohnkiteRotate" = "none";
      "kwin"."KrohnkiteRotatePart" = "none";
      "kwin"."KrohnkiteSetMaster" = "none";
      "kwin"."KrohnkiteShiftDown" = "Meta+Shift+J\\,none\\,Krohnkite: Move Down/Next";
      "kwin"."KrohnkiteShiftLeft" = "Meta+Shift+H\\,none\\,Krohnkite: Move Left";
      "kwin"."KrohnkiteShiftRight" = "Meta+Shift+L\\,none\\,Krohnkite: Move Right";
      "kwin"."KrohnkiteShiftUp" = "Meta+Shift+K\\,none\\,Krohnkite: Move Up/Prev";
      "kwin"."KrohnkiteShrinkHeight" = "Meta+Ctrl+K\\,none\\,Krohnkite: Shrink Height";
      "kwin"."KrohnkiteShrinkWidth" = "Meta+Ctrl+H\\,none\\,Krohnkite: Shrink Width";
      "kwin"."KrohnkiteSpiralLayout" = "none";
      "kwin"."KrohnkiteSpreadLayout" = "none";
      "kwin"."KrohnkiteStackedLayout" = "none";
      "kwin"."KrohnkiteStairLayout" = "none";
      "kwin"."KrohnkiteTileLayout" = "none";
      "kwin"."KrohnkiteToggleFloat" = "Meta+Shift+Space\\,none\\,Krohnkite: Toggle Float";
      "kwin"."KrohnkiteTreeColumnLayout" = "none";
      "kwin"."KrohnkitegrowWidth" = "Meta+Ctrl+L\\,none\\,Krohnkite: Grow Width";
      "kwin"."KrohnkitetoggleDock" = "none";

      "services/net.local.plasma-toggle-hdr.desktop"."_launch" = "Ctrl+Shift+B";
      "services/kitty.desktop"."_launch" = "Meta+Return";

      "services/org.kde.spectacle.desktop"."CurrentMonitorScreenShot" = "Ctrl+Shift+Home";
      "services/org.kde.spectacle.desktop"."RectangularRegionScreenShot" = ["Meta+Shift+Print" "Ctrl+Shift+PgUp"];
    };
  };

  home = {
    file =
    let sunshine-login = pkgs.writeShellScript "sunshine-login" ''
      if [ -f /tmp/sunshine_login ] && [[ "$XDG_CURRENT_DESKTOP" == "KDE" ]]; then
        if ${pkgs.gawk}/bin/awk '
        /CLIENT CONNECTED/ {e=1}
        e && /CLIENT DISCONNECTED/ {cancel=1}
        END { if (e && !cancel) exit 0; else exit 1 }
        ' <(${pkgs.gnused}/bin/sed ':a;N;$!ba;s/\n/ /g' /tmp/sunshine_login); then
          # Disable RGB
          ${pkgs.openrgb}/bin/openrgb --mode static --color 000000

          # Assume dummy display used for headless
          DUMMY="HDMI-A-1"
          
          ${pkgs.kdePackages.libkscreen}/bin/kscreen-doctor output."$DUMMY".enable
          
          output=$(${pkgs.kdePackages.libkscreen}/bin/kscreen-doctor -o)
          
          # Extract the names of the connected displays
          displays=$(echo "$output" | ${pkgs.gawk}/bin/awk '/Output:/ { print $3 }')
          echo "Displays found: $displays"

          # Check if the dummy display is present
          echo "$displays" | grep -qx "$DUMMY"
          if [ $? -ne 0 ]; then
            echo "$DUMMY is not connected."
          fi
          
          # Loop through each display and disable all except DUMMY
          while read -r display; do
            if [[ "$display" != "$DUMMY" ]]; then
              echo "Disabling display: $display"
              ${pkgs.kdePackages.libkscreen}/bin/kscreen-doctor output."$display".disable
            fi
          done <<< "$displays"

          systemctl --user start sunshine
        else
          # Get all connected and enabled outputs
          outputs=($(${pkgs.kdePackages.libkscreen}/bin/kscreen-doctor -j | ${pkgs.jq}/bin/jq -r '
            .outputs[]
            | select(.connected == true and .enabled == true)
            | .name
          '))
          
          len=''${#outputs[@]}
          first=''${outputs[0]:-}
          
          if [[ $len -eq 1 && ("$first" == "$DUMMY" || "$first" == "$DP-3") ]]; then
            echo "Only dummy is enabled and connected. Restoring..."
            ${pkgs.kdePackages.libkscreen}/bin/kscreen-doctor output.DP-1.enable
            ${pkgs.kdePackages.libkscreen}/bin/kscreen-doctor output.DP-2.enable
            ${pkgs.kdePackages.libkscreen}/bin/kscreen-doctor output.DP-3.disable
            ${pkgs.kdePackages.libkscreen}/bin/kscreen-doctor output."$DUMMY".disable
            ${pkgs.kdePackages.libkscreen}/bin/kscreen-doctor output.DP-1.primary
          else
            echo "Dummy is not the only enabled connected output"
          fi
        fi
      fi
    '';
    in {
      ".face.icon".source = ./.face.icon;
      ".config/autostart/sunshine-remote.desktop".text = ''
          [Desktop Entry]
          Type=Application
          Exec=${sunshine-login}
          Hidden=false
          NoDisplay=true
          X-GNOME-Autostart-enabled=true
          Name=My Script
          Comment=Checks for remote login and starts sunshine
        '';
    };

    packages = with pkgs; [
    ];
  };

  # https://nixos.wiki/wiki/FAQ/When_do_I_update_stateVersion
  home.stateVersion = "24.11";
}
