
# This is your home-manager configuration file
# Use this to configure your home environment (it replaces ~/.config/nixpkgs/home.nix)
{
  inputs,
  outputs,
  lib,
  config,
  pkgs,
  hostName,
  ...
}: {
  # You can import other home-manager modules here
  imports = [
    inputs.plasma-manager.homeManagerModules.plasma-manager
  ];

  nixpkgs = {
    # You can add overlays here
    overlays = [
      # Add overlays your own flake exports (from overlays and pkgs dir):
      outputs.overlays.additions
      outputs.overlays.modifications
      outputs.overlays.stable-packages
      outputs.overlays.unstable-packages
      outputs.overlays.legacy-packages
    ];
  };

  programs.plasma = {
    enable = true;
    overrideConfig = true;
    # Generated by "rc2nix" # nix run github:nix-community/plasma-manager"

    fonts = {
      general = {
        family = "Inter";
        pointSize = 10;
      };
      fixedWidth = {
        family = "Input Mono";
        pointSize = 10;
      };

      small = {
        family = config.programs.plasma.fonts.general.family;
        pointSize = 8;
      };
      toolbar = config.programs.plasma.fonts.general;
      menu = config.programs.plasma.fonts.general;
      windowTitle = config.programs.plasma.fonts.general;
    };
    
    kwin = {
      virtualDesktops = {
        number = 8;
        rows = 8;
      };
    };

    workspace = {
      # plasma-apply-desktoptheme --list-themes
      theme = "breeze-dark";
      # plasma-apply-colorscheme --list-schemes
      colorScheme = "BreezeDark";
      cursor = {
        theme = "XCursor-Pro-Dark";
        size = 24;
      };
      # ~/.config/kdeglobals
      iconTheme = "breeze-dark";
      wallpaper = "${./theming/wallpapers/new_gridania.jpg}";
      # plasma-apply-lookandfeel --list
      #lookAndFeel = "org.kde.breezedark.desktop";
    };

    # May need to delete ~/.config/kglobalshortcutsrc first to avoid weird shortcut clobbering
    shortcuts = {
	    # Disable to make way for Desktop shortcuts
	    #"plasmashell"."activate task manager entry 1" = "none,Meta+1,Activate Task Manager Entry 1";
	    #"plasmashell"."activate task manager entry 2" = "none,Meta+2,Activate Task Manager Entry 2";
	    #"plasmashell"."activate task manager entry 3" = "none,Meta+3,Activate Task Manager Entry 3";
	    #"plasmashell"."activate task manager entry 4" = "none,Meta+4,Activate Task Manager Entry 4";
	    #"plasmashell"."activate task manager entry 5" = "none,Meta+5,Activate Task Manager Entry 5";
	    #"plasmashell"."activate task manager entry 6" = "none,Meta+6,Activate Task Manager Entry 6";
	    #"plasmashell"."activate task manager entry 7" = "none,Meta+7,Activate Task Manager Entry 7";
	    #"plasmashell"."activate task manager entry 8" = "none,Meta+8,Activate Task Manager Entry 8";
	    #"plasmashell"."activate task manager entry 9" = "none,Meta+9,Activate Task Manager Entry 9";
	    #"plasmashell"."activate task manager entry 10" = "none,,Activate Task Manager Entry 10";
      #"kwin"."Show Desktop" = "none,Meta+D,Peek at Desktop";

      ksmserver = {
        "Lock Session" = "";
      };

      kwin = {
        "Window Close" = "Meta+Shift+Q";
        "Window Fullscreen" = "Meta+F";
        "Edit Tiles" = "Meta+T";

        "Switch to Desktop 1" = "Meta+1";
        "Switch to Desktop 2" = "Meta+2";
        "Switch to Desktop 3" = "Meta+3";
        "Switch to Desktop 4" = "Meta+4";
        "Switch to Desktop 5" = "Meta+5";
        "Switch to Desktop 6" = "Meta+6";
        "Switch to Desktop 7" = "Meta+7";
        "Switch to Desktop 8" = "Meta+8";
        "Switch to Desktop 9" = "Meta+9";
        "Switch to Desktop 10" = "Meta+0";

        "Window to Desktop 1" = "Meta+!";
        "Window to Desktop 2" = "Meta+@";
        "Window to Desktop 3" = "Meta+#";
        "Window to Desktop 4" = "Meta+$";
        "Window to Desktop 5" = "Meta+%";
        "Window to Desktop 6" = "Meta+^";
        "Window to Desktop 7" = "Meta+&";
        "Window to Desktop 8" = "Meta+*";
        "Window to Desktop 9" = "Meta+(";
        "Window to Desktop 10" = "Meta+)";

        # Unbind Meta+`
        "Walk Through Windows of Current Application" = "Alt+`";
        
        #"Window Move Center" = "Ctrl+Alt+C";
      };

      "services/org.kde.krunner.desktop"."_launch" = [ "Alt+F2" "Alt+Space" "Meta+D" "Search" ];

      #"kwin"."Window Close" = ["Alt+F4" "Meta+Shift+Q,Alt+F4,Close Window"];
      #"kwin"."Window Maximize" = ["Meta+PgUp" "Meta+F,Meta+PgUp,Maximize Window"];
      
      #"kwin"."KrohnkiteBTreeLayout" = "none";
      #"kwin"."KrohnkiteColumnsLayout" = "none";
      #"kwin"."KrohnkiteDecrease" = "none";
      #"kwin"."KrohnkiteFloatAll" = "Meta+Shift+F\\,none\\,Krohnkite: Toggle Float All";
      #"kwin"."KrohnkiteFloatingLayout" = "none";
      #"kwin"."KrohnkiteFocusDown" = "Meta+Down\\,none\\,Krohnkite: Focus Down";
      #"kwin"."KrohnkiteFocusLeft" = "Meta+Left\\,none\\,Krohnkite: Focus Left";
      #"kwin"."KrohnkiteFocusNext" = "none";
      #"kwin"."KrohnkiteFocusPrev" = "none";
      #"kwin"."KrohnkiteFocusRight" = "Meta+Right\\,none\\,Krohnkite: Focus Right";
      #"kwin"."KrohnkiteFocusUp" = "Meta+Up\\,none\\,Krohnkite: Focus Up";
      #"kwin"."KrohnkiteGrowHeight" = "Meta+Ctrl+J\\,none\\,Krohnkite: Grow Height";
      #"kwin"."KrohnkiteIncrease" = "Meta+I\\,none\\,Krohnkite: Increase";
      #"kwin"."KrohnkiteMonocleLayout" = "Meta+M\\,none\\,Krohnkite: Monocle Layout";
      #"kwin"."KrohnkiteNextLayout" = "Meta+\\\\\\,none\\,Krohnkite: Next Layout";
      #"kwin"."KrohnkitePreviousLayout" = "Meta+|\\,none\\,Krohnkite: Previous Layout";
      #"kwin"."KrohnkiteQuarterLayout" = "none";
      #"kwin"."KrohnkiteRotate" = "none";
      #"kwin"."KrohnkiteRotatePart" = "none";
      #"kwin"."KrohnkiteSetMaster" = "none";
      #"kwin"."KrohnkiteShiftDown" = "Meta+Shift+J\\,none\\,Krohnkite: Move Down/Next";
      #"kwin"."KrohnkiteShiftLeft" = "Meta+Shift+H\\,none\\,Krohnkite: Move Left";
      #"kwin"."KrohnkiteShiftRight" = "Meta+Shift+L\\,none\\,Krohnkite: Move Right";
      #"kwin"."KrohnkiteShiftUp" = "Meta+Shift+K\\,none\\,Krohnkite: Move Up/Prev";
      #"kwin"."KrohnkiteShrinkHeight" = "Meta+Ctrl+K\\,none\\,Krohnkite: Shrink Height";
      #"kwin"."KrohnkiteShrinkWidth" = "Meta+Ctrl+H\\,none\\,Krohnkite: Shrink Width";
      #"kwin"."KrohnkiteSpiralLayout" = "none";
      #"kwin"."KrohnkiteSpreadLayout" = "none";
      #"kwin"."KrohnkiteStackedLayout" = "none";
      #"kwin"."KrohnkiteStairLayout" = "none";
      #"kwin"."KrohnkiteTileLayout" = "none";
      #"kwin"."KrohnkiteToggleFloat" = "Meta+Shift+Space\\,none\\,Krohnkite: Toggle Float";
      #"kwin"."KrohnkiteTreeColumnLayout" = "none";
      #"kwin"."KrohnkitegrowWidth" = "Meta+Ctrl+L\\,none\\,Krohnkite: Grow Width";
      #"kwin"."KrohnkitetoggleDock" = "none";

      "services/net.local.plasma-toggle-hdr.desktop"."_launch" = "Ctrl+Shift+B";
      "services/kitty.desktop"."_launch" = "Meta+Return";

      "services/org.kde.spectacle.desktop"."CurrentMonitorScreenShot" = "Ctrl+Shift+Home";
      "services/org.kde.spectacle.desktop"."RectangularRegionScreenShot" = [ "Meta+Shift+Print" "Ctrl+Shift+PgUp" ];
    };

    panels = [
      {
        screen = "all";
        height = 22;
        location = "top";
        widgets = [
          "org.kde.plasma.kickoff"
          {
            name = "org.dhruv8sh.kara";
            config = {
              appearance = {
                showOnlyActive = true;
              };
              general = {
                animationDuration = 0;
                highlightOpacityFull = false;
                highlightType = 1; # Line
                spacing = 0;
                wrapOn = false;
              };
              type1 = {
                fixedLen = 3;
                labelSource = 0;
                t1activeWidth = 10;
              };
            };
          }
          {
          	name = "org.kde.plasma.icontasks";
          	config = {
          	  general = {
          	    showOnlyCurrentActivity = false;
          	    tooltipControls = false;
          	  };
          	};
          }
          "org.kde.plasma.panelspacer"
          {
            name = "org.kde.plasma.digitalclock";
            config = {
              Appearance = {
                autoFontAndSize = false;
                #customDateFormat = "ddd, MMM d";
                #dateDisplayFormat = "BesideTime";
                #dateFormat = "custom";
                showDate = false;
                fontSize = 10;
                fontFamily = "Inter Display";
                #fontStyleName = "Medium";
                fontWeight = 400;
                #use24hFormat = 2;
              };
            };
          }
          "org.kde.plasma.panelspacer"
          "org.kde.plasma.marginsseparator"
          {
            systemTray = {
              icons.scaleToFit = true;
              items = {
                showAll = false;
                shown = [
                  #"org.kde.plasma.keyboardlayout"
                  "org.kde.plasma.networkmanagement"
                  "org.kde.plasma.volume"
                ];
                hidden = [
                  "org.kde.plasma.battery"
                  "org.kde.plasma.brightness"
                  "org.kde.plasma.clipboard"
                  "org.kde.plasma.devicenotifier"
                  "org.kde.plasma.mediacontroller"
                  "plasmashell_microphone"
                  "xdg-desktop-portal-kde"
                  "zoom"
                ];
                configs = {
                  "org.kde.plasma.notifications".config = {
                    Shortcuts = {
                      global = "Meta+`";
                    };
                  };
                };
              };
            };
          }
        ];
      }
    ];

    configFile = {
      kwinrc = {
        #Desktops."Number" = {
        #  value = 8;
        #  # Forces kde to not change this value (even through the settings app).
        #  immutable = true;
        #};
        Plugins = {
          magiclampEnabled = true;
          "virtual-desktops-only-on-primaryEnabled" = true;
          forceblurEnabled = true; # Better Blur
        };
        "Script-virtual-desktops-only-on-primary" = {
          primaryOutputIndex = 0;
          numberOfScreens = 3;
        };
        Windows = {
          FocusPolicy = "FocusFollowsMouse";
        };
        EdgeBarrier.EdgeBarrier = 0;
        "Effect-slide"."SlideBackground" = false;

        # Better Blur
        "Effect-blurplus" = {
          BlurMatching = false;
          BlurNonMatching = true;
          BlurStrength = 5;
          Brightness = 1.7;
          Contrast = 1.2;
          Saturation = 1.2;
          NoiseStrength = 8;
          RefractionEdgeSize = 0;
          RefractionRGBFringing = 0;
          WindowClasses = "steam";
        };
      };
      kscreenlockerrc = {
        Daemon = {
          Autolock = false;
          Timeout = 0;
        };
      };
      spectaclerc = {
        General = {
          clipboardGroup = "PostScreenshotCopyImage";
          launchAction = "TakeFullscreenScreenshot";
          showCaptureInstructions = false;
        };
        GuiConfig.captureMode = 0;
      };
      kdeglobals = {
        General.accentColorFromWallpaper = true;
        Sounds.Enable = false;
      };
      plasmaparc.General.AudioFeedback = false;

      kdeglobals = {
        # For non-KDE desktops
        UiSettings.ColorScheme = "qt5ct";
      };

      dolphinrc = {
        DetailsMode.PreviewSize = 16; # Small icons in detail view
      };

      kcminputrc = {
        "Libinput/2362/628/PIXA3854:00 093A:0274 Touchpad".NaturalScroll = true;
      };
    };

    powerdevil = {
      AC = {
        autoSuspend = {
          action = "nothing";
          idleTimeout = null;
        };
        turnOffDisplay = {
          idleTimeout = "never";
          #idleTimeoutWhenLocked = 600;
        };
        dimDisplay = {
          enable = false;
          idleTimeout = null;
        };
        powerButtonAction = "lockScreen";
        whenSleepingEnter = "standby";
        inhibitLidActionWhenExternalMonitorConnected = true;
      };
      battery = {
        autoSuspend = {
          action = "nothing";
          idleTimeout = null;
        };
        turnOffDisplay = {
          idleTimeout = "never";
          #idleTimeoutWhenLocked = 600;
        };
        dimDisplay = {
          enable = false;
          idleTimeout = null;
        };
        powerButtonAction = "lockScreen";
        whenSleepingEnter = "standby";
        inhibitLidActionWhenExternalMonitorConnected = true;
      };
    };
  };

  home = {
    file =
    let sunshine-login = pkgs.writeShellScript "sunshine-login" ''
      if [ -f /tmp/sunshine_login ] && [[ "$XDG_CURRENT_DESKTOP" == "KDE" ]]; then
        if ${pkgs.gawk}/bin/awk '
        /CLIENT CONNECTED/ {e=1}
        e && /CLIENT DISCONNECTED/ {cancel=1}
        END { if (e && !cancel) exit 0; else exit 1 }
        ' <(${pkgs.gnused}/bin/sed ':a;N;$!ba;s/\n/ /g' /tmp/sunshine_login); then
          # Disable RGB
          ${pkgs.openrgb}/bin/openrgb --mode static --color 000000

          # Assume dummy display used for headless
          DUMMY="HDMI-A-1"
          
          ${pkgs.kdePackages.libkscreen}/bin/kscreen-doctor output."$DUMMY".enable
          
          output=$(${pkgs.kdePackages.libkscreen}/bin/kscreen-doctor -o)
          
          # Extract the names of the connected displays
          displays=$(echo "$output" | ${pkgs.gawk}/bin/awk '/Output:/ { print $3 }')
          echo "Displays found: $displays"

          # Check if the dummy display is present
          echo "$displays" | grep -qx "$DUMMY"
          if [ $? -ne 0 ]; then
            echo "$DUMMY is not connected."
          fi
          
          # Loop through each display and disable all except DUMMY
          while read -r display; do
            if [[ "$display" != "$DUMMY" ]]; then
              echo "Disabling display: $display"
              ${pkgs.kdePackages.libkscreen}/bin/kscreen-doctor output."$display".disable
            fi
          done <<< "$displays"

          systemctl --user start sunshine
        else
          # Get all connected and enabled outputs
          outputs=($(${pkgs.kdePackages.libkscreen}/bin/kscreen-doctor -j | ${pkgs.jq}/bin/jq -r '
            .outputs[]
            | select(.connected == true and .enabled == true)
            | .name
          '))
          
          len=''${#outputs[@]}
          first=''${outputs[0]:-}
          
          if [[ $len -eq 1 && ("$first" == "$DUMMY" || "$first" == "$DP-3") ]]; then
            echo "Only dummy is enabled and connected. Restoring..."
            ${pkgs.kdePackages.libkscreen}/bin/kscreen-doctor output.DP-1.enable
            ${pkgs.kdePackages.libkscreen}/bin/kscreen-doctor output.DP-2.enable
            ${pkgs.kdePackages.libkscreen}/bin/kscreen-doctor output.DP-3.disable
            ${pkgs.kdePackages.libkscreen}/bin/kscreen-doctor output."$DUMMY".disable
            ${pkgs.kdePackages.libkscreen}/bin/kscreen-doctor output.DP-1.primary
          else
            echo "Dummy is not the only enabled connected output"
          fi
        fi
      fi
    '';
    in {
      ".face.icon".source = ./.face.icon;
      ".config/autostart/sunshine-remote.desktop".text = ''
        [Desktop Entry]
        Type=Application
        Exec=${sunshine-login}
        Hidden=false
        NoDisplay=true
        X-GNOME-Autostart-enabled=true
        Name=My Script
        Comment=Checks for remote login and starts sunshine
      '';
    };
    sessionVariables = {
      # https://bugs.kde.org/show_bug.cgi?id=506645
      KWIN_DISABLE_TONEMAPPING = "1";
    };

    packages = with pkgs; [
      kdePackages.plasma-browser-integration
      colloid-kde
      kdePackages.krohnkite
      plasma-panel-colorizer
      plasma-toggle-hdr
      inputs.kwin-effects-forceblur.packages.${pkgs.system}.default
      kwin-effects-geometry-change
      virtual-desktops-only-on-primary
    ];
  };

  xdg.portal = {
    enable = true;
    extraPortals = with pkgs; [ kdePackages.xdg-desktop-portal-kde ];
  };

  # https://nixos.wiki/wiki/FAQ/When_do_I_update_stateVersion
  home.stateVersion = "24.11";
}
